const translations = {
  fr: {
    "title": "HolisticView",
    "header.logo": "HolisticView",
    "nav.home": "Accueil",
    "nav.about": "Société",
    "nav.solutions": "Solutions ▾",
    "nav.clients": "Clients",
    "nav.news": "Actualités",
    "nav.contact": "Contact",

    "btn.demo": "Demander une démo",
    "form.title": "Demande de démonstration",
    "form.subtitle": "Demande de démonstration",
    "form.name": "Nom complet :",
    "form.email": "Email :",
    "form.company": "Entreprise :",
    "form.function": "Fonction :",
    "form.selectFunction": "-- Sélectionnez votre fonction --",
    "form.func.direction": "Direction générale",
    "form.func.marketing": "Marketing / Communication",
    "form.func.commercial": "Commercial / Vente",
    "form.func.it": "Informatique / IT",
    "form.func.production": "Production / Exploitation",
    "form.func.qse": "Qualité / Sécurité / Environnement (QSE)",
    "form.func.logistique": "Logistique / Supply Chain",
    "form.func.achats": "Achats / Approvisionnement",
    "form.func.rh": "Ressources humaines",
    "form.func.finance": "Finance / Comptabilité",
    "form.func.support": "Support / Service client",
    "form.func.autre": "Autre",
    "form.sector": "Secteur :",
    "form.selectSector": "-- Sélectionnez votre secteur --",
    "form.sector.industrie": "Industrie",
    "form.sector.banque": "Banque / Assurance",
    "form.sector.tech": "Technologie / Informatique",
    "form.sector.sante": "Santé / Pharmaceutique",
    "form.sector.agro": "Agroalimentaire",
    "form.sector.commerce": "Commerce / Distribution",
    "form.sector.services": "Services",
    "form.sector.public": "Secteur public",
    "form.sector.transport": "Transport / Logistique",
    "form.sector.energie": "Énergie / Environnement",
    "form.sector.autre": "Autre",
    "form.message": "Message :",
    "form.submit": "Envoyer",
    "form.success": "✅ Merci pour votre contact !\nNous vous répondrons dans les plus brefs délais.",

    "solutions.dataConnexion": "Data connexion",
    "solutions.dataContext": "Data contextualisation",
    "solutions.rootCause": "Analyse des causes racine",
    "solutions.dataConnexionText": "Découvrez notre solution de data connexion pour intégrer vos machines et vos systèmes MES afin de collecter et centraliser vos données en temps réel.",
    "solutions.dataContextText": "Notre solution permet de contextualiser vos données industrielles pour faciliter l’analyse et la prise de décision.",
    "solutions.rootCauseText": "Cette solution vous aide à identifier les causes principales des incidents pour améliorer vos processus et réduire les pertes.",


    "contact.titl": "Contactez-nous",
    "contact.text2": "Vous avez une question ou vous souhaitez nous faire part de votre projet de MES ? L’équipe vous répondra au plus vite",


    "contact.title": "Contactez-nous et boostez votre productivité !",
    "contact.text1": "Prêt à franchir le cap de la digitalisation industrielle ? <strong>Contactez notre équipe</strong> et découvrez comment <strong>Holistic View MES</strong> peut améliorer votre <strong>TRS</strong>, votre consommation énergétique et votre suivi qualité.",
    "contact.text2": "Parlez-nous de votre projet et obtenez une démonstration personnalisée !",
    "contact.label.nom": "Nom :",
    "contact.label.prenom": "Prénom :",
    "contact.label.societe": "Société :",
    "contact.label.email": "E-mail :",
    "contact.label.source": "Comment avez-vous entendu parler de nous ?",
    "form.source1": "Réseaux sociaux",
    "form.source2": "Recommandation",
    "form.source3": "Salon professionnel",
    "form.source4": "Moteur de recherche ",
    "form.source5": "Autre",
    "contact.label.objet": "Objet :",
    "contact.label.message": "Votre message :",
    "contact.btn.envoyer": "Envoyer",

    "footer.company": "HOLISTIC VIEW",
    "footer.address": "1, rue Henri Spriet, 14120 Mondeville",
    "footer.phone": "09 71 12 01 73",
    "footer.email": "contact[@]holisticview.com",
    "footer.newsTitle": "Dernières actus",
    "footer.news1": "Salon SEPEM Angers 2025",
    "footer.news2": "Salon Prod&Pack Lyon 2025",
    "footer.news3": "Article thématique : Le Management visuel",
    "footer.news4": "Partenariat Sofrastock",
    "footer.info": "Informations utiles",
    "footer.about": "Société Holistic View",
    "footer.contact": "Contactez-nous",
    "footer.demo": "Demander une démonstration",
    "footer.legal": "Mentions légales",
    "footer.sitemap": "Plan du site",
    "social.text": "Retrouvez-nous sur <strong>LinkedIn</strong>",
    

   "dc_image": "maintenance",
  
    



  },
  en: {



    "dc_image": "maintenanc",
    "title": "HolisticView",
    "header.logo": "HolisticView",
    "nav.home": "Home",
    "nav.about": "Company",
    "nav.solutions": "Solutions ▾",
    "nav.clients": "Clients",
    "nav.news": "News",
    "nav.contact": "Contact",

    "btn.demo": "Ask a Demo",
    "form.title": "Ask for a demo",
    "form.subtitle": "Ask for a demo",
    "form.name": "Full Name:",
    "form.email": "Email:",
    "form.company": "Company:",
    "form.function": "Function:",
    "form.selectFunction": "-- Select your function --",
    "form.func.direction": "General Management",
    "form.func.marketing": "Marketing / Communication",
    "form.func.commercial": "Sales",
    "form.func.it": "IT",
    "form.func.production": "Production / Operations",
    "form.func.qse": "Quality / Safety / Environment (QSE)",
    "form.func.logistique": "Logistics / Supply Chain",
    "form.func.achats": "Purchasing",
    "form.func.rh": "Human Resources",
    "form.func.finance": "Finance / Accounting",
    "form.func.support": "Support / Customer Service",
    "form.func.autre": "Other",
    "form.sector": "Sector:",
    "form.selectSector": "-- Select your sector --",
    "form.sector.industrie": "Industry",
    "form.sector.banque": "Banking / Insurance",
    "form.sector.tech": "Technology / IT",
    "form.sector.sante": "Health / Pharmaceutical",
    "form.sector.agro": "Agro-food",
    "form.sector.commerce": "Commerce / Distribution",
    "form.sector.services": "Services",
    "form.sector.public": "Public Sector",
    "form.sector.transport": "Transport / Logistics",
    "form.sector.energie": "Energy / Environment",
    "form.sector.autre": "Other",
    "form.message": "Message:",
    "form.submit": "Send",
    "form.success": "✅ Thank you for contacting us!\nWe will reply as soon as possible.",

    "solutions.dataConnexion": "Data connection",
    "solutions.dataContext": "Data contextualization",
    "solutions.rootCause": "Root cause analysis",
    "solutions.dataConnexionText": "Discover our data connection solution to integrate your machines and MES systems, collecting and centralizing your data in real time.",
    "solutions.dataContextText": "Our solution contextualizes your industrial data to facilitate analysis and decision-making.",
    "solutions.rootCauseText": "This solution helps identify the root causes of incidents to improve processes and reduce losses.",

    "contact.titl": "Contact Us",
    "contact.text2": "Do you have a question or would you like to tell us about your MES project? Our team will get back to you as soon as possible.",



    "contact.title": "Contact us and boost your productivity!",
    "contact.text1": "Ready to take the leap into industrial digitalization? <strong>Contact our team</strong> and discover how <strong>Holistic View MES</strong> can improve your <strong>OEE</strong>, energy consumption, and quality tracking.",
    "contact.text2": "Tell us about your project and get a personalized demo!",
    "contact.label.nom": "Last name:",
    "contact.label.prenom": "First name:",
    "contact.label.societe": "Company:",
    "contact.label.email": "Email:",
    "contact.label.source": "How did you hear about us?",
    "form.source1": "Social media",
    "form.source2": "Recommendation",
    "form.source3": "Trade fair",
    "form.source4": "search engine",
    "form.source5": "Other",
    "contact.label.objet": "Subject:",
    "contact.label.message": "Your message:",
    "contact.btn.envoyer": "Send",

    "footer.company": "HOLISTIC VIEW",
    "footer.address": "1, rue Henri Spriet, 14120 Mondeville, France",
    "footer.phone": "+33 9 71 12 01 73",
    "footer.email": "contact[@]holisticview.com",
    "footer.newsTitle": "Latest news",
    "footer.news1": "SEPEM Angers 2025",
    "footer.news2": "Prod&Pack Lyon 2025",
    "footer.news3": "Thematic article: Visual Management",
    "footer.news4": "Sofrastock Partnership",
    "footer.info": "Useful information",
    "footer.about": "About Holistic View",
    "footer.contact": "Contact us",
    "footer.demo": "Request a demo",
    "footer.legal": "Legal notice",
    "footer.sitemap": "Site map",
    "social.text": "Follow us on <strong>LinkedIn</strong>"
  }
};

function setLanguage(lang) {
  localStorage.setItem("lang", lang);
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang][key]) el.innerHTML = translations[lang][key];
  });
}
